# Generated by Django 2.1.7 on 2019-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0003_auto_20190330_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='summary',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
